# SPDX-License-Identifier: MIT-0
---
# tasks file for nginx

- name: Install nginx
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present

- name: Copy configuration from template
  ansible.builtin.template:
    src: php_blog.conf.j2
    dest: /etc/nginx/sites-available/php_blog.conf
    owner: www-data
    group: www-data
    mode: "0755"
  notify: Reload nginx

- name: Creating configuration symlink
  ansible.builtin.file:
    src: /etc/nginx/sites-available/php_blog.conf
    dest: /etc/nginx/sites-enabled/php_blog
    owner: www-data
    group: www-data
    state: link

- name: Deleting default symlink
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
